steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'us-west3-docker.pkg.dev/refined-core-464919-u5/flask-hello-repo/flask-hello:latest', '.']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'us-west3-docker.pkg.dev/refined-core-464919-u5/flask-hello-repo/flask-hello:latest']
  - name: 'gcr.io/cloud-builders/gke-delpoy'
    args:
      - 'run'
      - '--filename=gke.yaml'
      - '--image=us-west3-docker.pkg.dev/refined-core-464919-u5/flask-hello-repo/flask-hello:latest'
      - '--cluster=autopilot-cluster-1'
      - '--location=us-west3'
      - '--namespace=gcp-test'
options:
    logging: 'CLOUD_LOGGING_ONLY'